from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import StreamingResponse
from slowapi import Limiter
from slowapi.util import get_remote_address
from app.backend.models.chat import ChatRequest, ChatResponse
from app.backend.services.rag_service import build_augmented_prompt, get_relevant_context
from app.backend.services.vector_store import vector_store
from app.thirdparty_API.geminiAPI import generate_content_stream, generate_content_async
from app.middleware.security import sanitize_text, validate_message_length, truncate_conversation_history
from app.middleware.settings.settings import config
import json
import asyncio

router = APIRouter()
limiter = Limiter(key_func=get_remote_address)


@router.post("/stream")
@limiter.limit(config.RATE_LIMIT_CHAT)
async def chat_stream(chat_request: ChatRequest, request: Request):
    """
    Stream chat response using Server-Sent Events (SSE).

    The response is streamed word-by-word as it's generated by the AI.

    Rate limit: 10 requests per minute per IP
    """
    # Validate message length
    if not validate_message_length(chat_request.message):
        raise HTTPException(
            status_code=400,
            detail=f"Message too long. Maximum {config.MAX_MESSAGE_LENGTH} characters allowed."
        )

    # Sanitize user input
    sanitized_message = sanitize_text(chat_request.message)

    # Truncate conversation history
    sanitized_history = truncate_conversation_history(chat_request.conversation_history)

    async def event_generator():
        try:
            # Build the prompt
            if chat_request.use_rag and vector_store.index.ntotal > 0:
                # Get relevant context using RAG
                context_chunks = await get_relevant_context(
                    query=sanitized_message,
                    vector_store=vector_store
                )
                prompt = build_augmented_prompt(
                    query=sanitized_message,
                    context_chunks=context_chunks,
                    conversation_history=[msg.dict() for msg in sanitized_history]
                )

                # Send sources information first
                if context_chunks:
                    sources = list(set([filename for _, _, filename in context_chunks]))
                    yield f"data: {json.dumps({'sources': sources})}\n\n"
            else:
                # No RAG, just use the message as prompt
                if sanitized_history:
                    history_text = "\n".join([
                        f"{msg.role}: {msg.content}"
                        for msg in sanitized_history[-5:]
                    ])
                    prompt = f"Previous conversation:\n{history_text}\n\nUser: {sanitized_message}\nAssistant:"
                else:
                    prompt = sanitized_message

            # Stream response from Gemini
            for chunk in generate_content_stream(prompt):
                # Send text chunk
                yield f"data: {json.dumps({'text': chunk})}\n\n"
                # Small delay to prevent overwhelming the client
                await asyncio.sleep(0.01)

            # Send completion signal
            yield f"data: {json.dumps({'done': True})}\n\n"

        except Exception as e:
            error_message = f"Error generating response: {str(e)}"
            yield f"data: {json.dumps({'error': error_message})}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",  # Disable buffering in nginx
        }
    )


@router.post("/", response_model=ChatResponse)
@limiter.limit(config.RATE_LIMIT_CHAT)
async def chat(chat_request: ChatRequest, request: Request):
    """
    Non-streaming chat endpoint.

    Returns the complete response at once.

    Rate limit: 10 requests per minute per IP
    """
    # Validate message length
    if not validate_message_length(chat_request.message):
        raise HTTPException(
            status_code=400,
            detail=f"Message too long. Maximum {config.MAX_MESSAGE_LENGTH} characters allowed."
        )

    # Sanitize user input
    sanitized_message = sanitize_text(chat_request.message)

    # Truncate conversation history
    sanitized_history = truncate_conversation_history(chat_request.conversation_history)

    try:
        # Build the prompt
        if chat_request.use_rag and vector_store.index.ntotal > 0:
            # Get relevant context using RAG
            context_chunks = await get_relevant_context(
                query=sanitized_message,
                vector_store=vector_store
            )
            prompt = build_augmented_prompt(
                query=sanitized_message,
                context_chunks=context_chunks,
                conversation_history=[msg.dict() for msg in sanitized_history]
            )
            sources = list(set([filename for _, _, filename in context_chunks]))
        else:
            # No RAG
            if sanitized_history:
                history_text = "\n".join([
                    f"{msg.role}: {msg.content}"
                    for msg in sanitized_history[-5:]
                ])
                prompt = f"Previous conversation:\n{history_text}\n\nUser: {sanitized_message}\nAssistant:"
            else:
                prompt = sanitized_message
            sources = []

        # Generate response
        response_text = await generate_content_async(prompt)

        return ChatResponse(
            response=response_text,
            sources=sources
        )

    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Error generating response: {str(e)}"
        )
