from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from app.backend.models.chat import ChatRequest, ChatResponse
from app.backend.services.rag_service import build_augmented_prompt, get_relevant_context
from app.backend.services.vector_store import vector_store
from app.thirdparty_API.geminiAPI import generate_content_stream, generate_content_async
import json
import asyncio

router = APIRouter()


@router.post("/stream")
async def chat_stream(request: ChatRequest):
    """
    Stream chat response using Server-Sent Events (SSE).

    The response is streamed word-by-word as it's generated by the AI.
    """
    async def event_generator():
        try:
            # Build the prompt
            if request.use_rag and vector_store.index.ntotal > 0:
                # Get relevant context using RAG
                context_chunks = await get_relevant_context(
                    query=request.message,
                    vector_store=vector_store
                )
                prompt = build_augmented_prompt(
                    query=request.message,
                    context_chunks=context_chunks,
                    conversation_history=[msg.dict() for msg in request.conversation_history]
                )

                # Send sources information first
                if context_chunks:
                    sources = list(set([filename for _, _, filename in context_chunks]))
                    yield f"data: {json.dumps({'sources': sources})}\n\n"
            else:
                # No RAG, just use the message as prompt
                if request.conversation_history:
                    history_text = "\n".join([
                        f"{msg.role}: {msg.content}"
                        for msg in request.conversation_history[-5:]
                    ])
                    prompt = f"Previous conversation:\n{history_text}\n\nUser: {request.message}\nAssistant:"
                else:
                    prompt = request.message

            # Stream response from Gemini
            for chunk in generate_content_stream(prompt):
                # Send text chunk
                yield f"data: {json.dumps({'text': chunk})}\n\n"
                # Small delay to prevent overwhelming the client
                await asyncio.sleep(0.01)

            # Send completion signal
            yield f"data: {json.dumps({'done': True})}\n\n"

        except Exception as e:
            error_message = f"Error generating response: {str(e)}"
            yield f"data: {json.dumps({'error': error_message})}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",  # Disable buffering in nginx
        }
    )


@router.post("/", response_model=ChatResponse)
async def chat(request: ChatRequest):
    """
    Non-streaming chat endpoint.

    Returns the complete response at once.
    """
    try:
        # Build the prompt
        if request.use_rag and vector_store.index.ntotal > 0:
            # Get relevant context using RAG
            context_chunks = await get_relevant_context(
                query=request.message,
                vector_store=vector_store
            )
            prompt = build_augmented_prompt(
                query=request.message,
                context_chunks=context_chunks,
                conversation_history=[msg.dict() for msg in request.conversation_history]
            )
            sources = list(set([filename for _, _, filename in context_chunks]))
        else:
            # No RAG
            if request.conversation_history:
                history_text = "\n".join([
                    f"{msg.role}: {msg.content}"
                    for msg in request.conversation_history[-5:]
                ])
                prompt = f"Previous conversation:\n{history_text}\n\nUser: {request.message}\nAssistant:"
            else:
                prompt = request.message
            sources = []

        # Generate response
        response_text = await generate_content_async(prompt)

        return ChatResponse(
            response=response_text,
            sources=sources
        )

    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Error generating response: {str(e)}"
        )
